In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# LSTM and GRU DIAGRAM

![LSTM Model](https://daxg39y63pxwu.cloudfront.net/images/blog/lstm-model/Long_Short_Term_Memory_(LSTM)_Models.webp)

![GRU Architecture](https://media.geeksforgeeks.org/wp-content/uploads/20260305160758210335/GRU_1.webp)

# Sentence Completion

In [2]:
df = pd.read_csv("qoute_dataset.csv")

In [3]:
df.head()

                                               quote           Author
0  “The world as we have created it is a process ...  Albert Einstein
1  “It is our choices, Harry, that show what we t...     J.K. Rowling
2  “There are only two ways to live your life. On...  Albert Einstein
3  “The person, be it gentleman or lady, who has ...      Jane Austen
4  “Imperfection is beauty, madness is genius and...   Marilyn Monroe

In [4]:
df.shape

(3038, 2)

In [5]:
quotes = df['quote']
quotes.head()

0    “The world as we have created it is a process ...
1    “It is our choices, Harry, that show what we t...
2    “There are only two ways to live your life. On...
3    “The person, be it gentleman or lady, who has ...
4    “Imperfection is beauty, madness is genius and...
Name: quote, dtype: object

In [6]:
quotes = quotes.str.lower()

In [7]:
import string
# Removing Punctuations
translator = str.maketrans('','',string.punctuation)
quotes = quotes.apply(lambda x: x.translate(translator))

In [8]:
quotes.head()

0    “the world as we have created it is a process ...
1    “it is our choices harry that show what we tru...
2    “there are only two ways to live your life one...
3    “the person be it gentleman or lady who has no...
4    “imperfection is beauty madness is genius and ...
Name: quote, dtype: object

In [9]:
from tensorflow.keras.preprocessing.text import Tokenizer

In [10]:
vocab_size = 8978

tokenizer = Tokenizer(num_words = vocab_size)
tokenizer.fit_on_texts(quotes)

In [11]:
word_index = tokenizer.word_index
print(len(word_index))
list(word_index.items())[:10 ]

8978

[('the', 1),
 ('you', 2),
 ('to', 3),
 ('and', 4),
 ('a', 5),
 ('i', 6),
 ('is', 7),
 ('of', 8),
 ('that', 9),
 ('it', 10)]

In [12]:
sequence = tokenizer.texts_to_sequences(quotes)

In [13]:
quotes[0]

'“the world as we have created it is a process of our thinking it cannot be changed without changing our thinking”'

In [14]:
print(sequence[0])

[713, 62, 29, 19, 16, 946, 10, 7, 5, 1156, 8, 70, 293, 10, 145, 12, 809, 104, 752, 70, 2461]

In [15]:
X = []
y = []

for seq in sequence:
    for i in range(1, len(seq)):
      input_seq = seq[:i]
      output_seq = seq[i]
      X.append(input_seq)
      y.append(output_seq)

In [16]:
len(X)

85270

In [17]:
max_len = max(len(x) for x in X)
print(max_len)

745

In [18]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [19]:
X_padded = pad_sequences(X,maxlen=max_len,padding = 'pre')

In [20]:
X_padded

array([[   0,    0,    0, ...,    0,    0,  713],
       [   0,    0,    0, ...,    0,  713,   62],
       [   0,    0,    0, ...,  713,   62,   29],
       ...,
       [   0,    0,    0, ...,    9,   19, 1125],
       [   0,    0,    0, ...,   19, 1125,    3],
       [   0,    0,    0, ..., 1125,    3,  169]], dtype=int32)

In [21]:
y = np.array(y)

In [22]:
X_padded.shape

(85270, 745)

In [23]:
y.shape

(85270,)

In [24]:
from tensorflow.keras.utils import to_categorical
y_one_hot = to_categorical(y,num_classes = vocab_size)

In [25]:
y_one_hot.shape

(85270, 8978)

### Creating the model

In [26]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense,LSTM

In [27]:
embedding_dim = 50
rnn_units = 128

In [28]:
rnn_model = Sequential()

rnn_model.add(
    Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len)
)

rnn_model.add(SimpleRNN(units = rnn_units))

# O/p Layer
rnn_model.add(Dense(vocab_size,activation='softmax'))

In [29]:
rnn_model.compile(
optimizer='adam',
loss='categorical_crossentropy',
metrics=['accuracy']
)

In [30]:
rnn_model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn (SimpleRNN)          │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [31]:
lstm_model = Sequential()
lstm_model.add(Embedding(input_dim=vocab_size,output_dim=embedding_dim,input_length=max_len))
lstm_model.add(LSTM(units=rnn_units))
lstm_model.add(Dense(vocab_size,activation='softmax'))

In [32]:
lstm_model.compile(
optimizer='adam',
loss='categorical_crossentropy',
metrics=['accuracy']
)

In [33]:
lstm_model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm (LSTM)                     │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [34]:
epochs = 10
batch_size = 128

In [35]:
# history = rnn_model.fit(
#     X_padded,
#     y_one_hot,
#     epochs=epochs,
#     batch_size=batch_size,
#     validation_split=0.2
# )

In [36]:
history = lstm_model.fit(
    X_padded,
    y_one_hot,
    epochs=100,
    batch_size=batch_size,
    validation_split=0.2
)

Epoch 1/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 36s 56ms/step - accuracy: 0.0385 - loss: 6.7546 - val_accuracy: 0.0429 - val_loss: 6.7356
Epoch 2/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 29s 55ms/step - accuracy: 0.0548 - loss: 6.3338 - val_accuracy: 0.0612 - val_loss: 6.6399
Epoch 3/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 56ms/step - accuracy: 0.0733 - loss: 6.0910 - val_accuracy: 0.0788 - val_loss: 6.5382
Epoch 4/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.0928 - loss: 5.8887 - val_accuracy: 0.0908 - val_loss: 6.5162
Epoch 5/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.1047 - loss: 5.7161 - val_accuracy: 0.0942 - val_loss: 6.5122
Epoch 6/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.1126 - loss: 5.5554 - val_accuracy: 0.0984 - val_loss: 6.5292
Epoch 7/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.1226 - loss: 5.4006 - val_accuracy: 0.1042 - val_loss: 6.5378
Epoch 8/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1308 - loss: 5.2474 - val_accuracy: 0.1036 - val_loss: 6.5683
Epoch 9/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1401 - loss: 5.1024 - val_accuracy: 0.1085 - val_loss: 6.6009
Epoch 10/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.1466 - loss: 4.9648 - val_accuracy: 0.1073 - val_loss: 6.6359
Epoch 11/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.1538 - loss: 4.8336 - val_accuracy: 0.1114 - val_loss: 6.6839
Epoch 12/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.1617 - loss: 4.7049 - val_accuracy: 0.1108 - val_loss: 6.7496
Epoch 13/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.1700 - loss: 4.5805 - val_accuracy: 0.1108 - val_loss: 6.8070
Epoch 14/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.1794 - loss: 4.4580 - val_accuracy: 0.1109 - val_loss: 6.8797
Epoch 15/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.1891 - loss: 4.3407 - val_accuracy: 0.1119 - val_loss: 6.9394
Epoch 16/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 57ms/step - accuracy: 0.2003 - loss: 4.2247 - val_accuracy: 0.1119 - val_loss: 7.0094
Epoch 17/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.2145 - loss: 4.1123 - val_accuracy: 0.1098 - val_loss: 7.0839
Epoch 18/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 56ms/step - accuracy: 0.2285 - loss: 4.0043 - val_accuracy: 0.1091 - val_loss: 7.1585
Epoch 19/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.2421 - loss: 3.9007 - val_accuracy: 0.1105 - val_loss: 7.2391
Epoch 20/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2564 - loss: 3.8013 - val_accuracy: 0.1088 - val_loss: 7.3198
Epoch 21/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.2691 - loss: 3.7093 - val_accuracy: 0.1091 - val_loss: 7.3910
Epoch 22/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.2838 - loss: 3.6214 - val_accuracy: 0.1072 - val_loss: 7.4721
Epoch 23/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.2968 - loss: 3.5397 - val_accuracy: 0.1085 - val_loss: 7.5429
Epoch 24/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3080 - loss: 3.4611 - val_accuracy: 0.1064 - val_loss: 7.6153
Epoch 25/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 58ms/step - accuracy: 0.3194 - loss: 3.3894 - val_accuracy: 0.1076 - val_loss: 7.7036
Epoch 26/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.3316 - loss: 3.3188 - val_accuracy: 0.1060 - val_loss: 7.7635
Epoch 27/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.3416 - loss: 3.2534 - val_accuracy: 0.1022 - val_loss: 7.8449
Epoch 28/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3512 - loss: 3.1911 - val_accuracy: 0.1023 - val_loss: 7.9088
Epoch 29/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3605 - loss: 3.1298 - val_accuracy: 0.1034 - val_loss: 7.9900
Epoch 30/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3698 - loss: 3.0717 - val_accuracy: 0.1019 - val_loss: 8.0538
Epoch 31/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3795 - loss: 3.0177 - val_accuracy: 0.1044 - val_loss: 8.1223
Epoch 32/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.3889 - loss: 2.9654 - val_accuracy: 0.1006 - val_loss: 8.1901
Epoch 33/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.3969 - loss: 2.9112 - val_accuracy: 0.0999 - val_loss: 8.2779
Epoch 34/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4053 - loss: 2.8620 - val_accuracy: 0.0989 - val_loss: 8.3303
Epoch 35/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4135 - loss: 2.8123 - val_accuracy: 0.0996 - val_loss: 8.3870
Epoch 36/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4233 - loss: 2.7652 - val_accuracy: 0.0988 - val_loss: 8.4637
Epoch 37/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4304 - loss: 2.7199 - val_accuracy: 0.0953 - val_loss: 8.5090
Epoch 38/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4386 - loss: 2.6758 - val_accuracy: 0.0962 - val_loss: 8.5693
Epoch 39/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4454 - loss: 2.6327 - val_accuracy: 0.0969 - val_loss: 8.6485
Epoch 40/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4541 - loss: 2.5898 - val_accuracy: 0.0959 - val_loss: 8.6960
Epoch 41/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 59ms/step - accuracy: 0.4613 - loss: 2.5491 - val_accuracy: 0.0966 - val_loss: 8.7673
Epoch 42/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.4688 - loss: 2.5090 - val_accuracy: 0.0936 - val_loss: 8.8005
Epoch 43/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4759 - loss: 2.4702 - val_accuracy: 0.0944 - val_loss: 8.8754
Epoch 44/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.4826 - loss: 2.4318 - val_accuracy: 0.0925 - val_loss: 8.9571
Epoch 45/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.4890 - loss: 2.3944 - val_accuracy: 0.0922 - val_loss: 9.0023
Epoch 46/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.4964 - loss: 2.3585 - val_accuracy: 0.0918 - val_loss: 9.0646
Epoch 47/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5019 - loss: 2.3223 - val_accuracy: 0.0912 - val_loss: 9.1053
Epoch 48/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.5104 - loss: 2.2875 - val_accuracy: 0.0929 - val_loss: 9.1708
Epoch 49/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5166 - loss: 2.2534 - val_accuracy: 0.0897 - val_loss: 9.2325
Epoch 50/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5226 - loss: 2.2201 - val_accuracy: 0.0914 - val_loss: 9.2615
Epoch 51/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5293 - loss: 2.1879 - val_accuracy: 0.0896 - val_loss: 9.3499
Epoch 52/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5345 - loss: 2.1580 - val_accuracy: 0.0897 - val_loss: 9.3944
Epoch 53/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5405 - loss: 2.1249 - val_accuracy: 0.0885 - val_loss: 9.4454
Epoch 54/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5466 - loss: 2.0956 - val_accuracy: 0.0891 - val_loss: 9.4977
Epoch 55/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5530 - loss: 2.0644 - val_accuracy: 0.0886 - val_loss: 9.5727
Epoch 56/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 42s 59ms/step - accuracy: 0.5599 - loss: 2.0359 - val_accuracy: 0.0870 - val_loss: 9.6118
Epoch 57/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.5649 - loss: 2.0068 - val_accuracy: 0.0842 - val_loss: 9.6779
Epoch 58/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.5697 - loss: 1.9809 - val_accuracy: 0.0864 - val_loss: 9.7229
Epoch 59/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5769 - loss: 1.9519 - val_accuracy: 0.0874 - val_loss: 9.7991
Epoch 60/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 32s 61ms/step - accuracy: 0.5813 - loss: 1.9263 - val_accuracy: 0.0844 - val_loss: 9.8277
Epoch 61/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.5871 - loss: 1.8983 - val_accuracy: 0.0848 - val_loss: 9.8792
Epoch 62/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 40s 58ms/step - accuracy: 0.5919 - loss: 1.8737 - val_accuracy: 0.0847 - val_loss: 9.9195
Epoch 63/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.5969 - loss: 1.8487 - val_accuracy: 0.0837 - val_loss: 9.9775
Epoch 64/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6024 - loss: 1.8229 - val_accuracy: 0.0851 - val_loss: 10.0344
Epoch 65/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6073 - loss: 1.8000 - val_accuracy: 0.0841 - val_loss: 10.0936
Epoch 66/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6125 - loss: 1.7762 - val_accuracy: 0.0832 - val_loss: 10.1324
Epoch 67/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6171 - loss: 1.7530 - val_accuracy: 0.0822 - val_loss: 10.1912
Epoch 68/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6218 - loss: 1.7291 - val_accuracy: 0.0830 - val_loss: 10.2272
Epoch 69/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6270 - loss: 1.7063 - val_accuracy: 0.0803 - val_loss: 10.2873
Epoch 70/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6326 - loss: 1.6848 - val_accuracy: 0.0808 - val_loss: 10.3260
Epoch 71/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6367 - loss: 1.6641 - val_accuracy: 0.0795 - val_loss: 10.3866
Epoch 72/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6409 - loss: 1.6420 - val_accuracy: 0.0805 - val_loss: 10.4468
Epoch 73/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6445 - loss: 1.6240 - val_accuracy: 0.0807 - val_loss: 10.4767
Epoch 74/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6488 - loss: 1.6014 - val_accuracy: 0.0813 - val_loss: 10.5454
Epoch 75/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.6537 - loss: 1.5815 - val_accuracy: 0.0787 - val_loss: 10.5865
Epoch 76/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6559 - loss: 1.5632 - val_accuracy: 0.0803 - val_loss: 10.6160
Epoch 77/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6609 - loss: 1.5432 - val_accuracy: 0.0797 - val_loss: 10.6621
Epoch 78/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6660 - loss: 1.5239 - val_accuracy: 0.0796 - val_loss: 10.7083
Epoch 79/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 41s 58ms/step - accuracy: 0.6699 - loss: 1.5047 - val_accuracy: 0.0803 - val_loss: 10.7866
Epoch 80/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6721 - loss: 1.4914 - val_accuracy: 0.0796 - val_loss: 10.8296
Epoch 81/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6759 - loss: 1.4696 - val_accuracy: 0.0819 - val_loss: 10.8603
Epoch 82/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6807 - loss: 1.4524 - val_accuracy: 0.0786 - val_loss: 10.9204
Epoch 83/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6854 - loss: 1.4341 - val_accuracy: 0.0783 - val_loss: 10.9775
Epoch 84/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6886 - loss: 1.4184 - val_accuracy: 0.0770 - val_loss: 11.0071
Epoch 85/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.6914 - loss: 1.4021 - val_accuracy: 0.0779 - val_loss: 11.0506
Epoch 86/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.6939 - loss: 1.3853 - val_accuracy: 0.0765 - val_loss: 11.0980
Epoch 87/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.6985 - loss: 1.3686 - val_accuracy: 0.0772 - val_loss: 11.1611
Epoch 88/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7015 - loss: 1.3542 - val_accuracy: 0.0772 - val_loss: 11.1923
Epoch 89/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7060 - loss: 1.3383 - val_accuracy: 0.0775 - val_loss: 11.2270
Epoch 90/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7091 - loss: 1.3227 - val_accuracy: 0.0766 - val_loss: 11.2805
Epoch 91/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7111 - loss: 1.3086 - val_accuracy: 0.0776 - val_loss: 11.3298
Epoch 92/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7137 - loss: 1.2937 - val_accuracy: 0.0763 - val_loss: 11.3766
Epoch 93/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7181 - loss: 1.2782 - val_accuracy: 0.0759 - val_loss: 11.4302
Epoch 94/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7206 - loss: 1.2661 - val_accuracy: 0.0761 - val_loss: 11.4659
Epoch 95/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 33s 61ms/step - accuracy: 0.7242 - loss: 1.2501 - val_accuracy: 0.0754 - val_loss: 11.5143
Epoch 96/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7276 - loss: 1.2356 - val_accuracy: 0.0758 - val_loss: 11.5372
Epoch 97/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7308 - loss: 1.2232 - val_accuracy: 0.0752 - val_loss: 11.6003
Epoch 98/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 57ms/step - accuracy: 0.7320 - loss: 1.2093 - val_accuracy: 0.0739 - val_loss: 11.6399
Epoch 99/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 31s 58ms/step - accuracy: 0.7357 - loss: 1.1960 - val_accuracy: 0.0749 - val_loss: 11.6778
Epoch 100/100
533/533 ━━━━━━━━━━━━━━━━━━━━ 30s 57ms/step - accuracy: 0.7391 - loss: 1.1841 - val_accuracy: 0.0748 - val_loss: 11.7335

In [37]:
lstm_model.save("lstm_model.h5")

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
# from tensorflow.keras.models import load_model

#lstm_model = load_model("next_word_model.h5")

In [38]:
index_to_word = {}
for word, index in word_index.items():
    index_to_word[index] = word

In [41]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [42]:
def predictor(model,tokenizer,text,max_len):
  text = text.lower()

  seq = tokenizer.texts_to_sequences([text])
  seq = pad_sequences(seq,maxlen=max_len,padding='pre')

  pred = model.predict(seq,verbose = 0)
  pred_word_index = np.argmax(pred)
  predicted_word = index_to_word[pred_word_index]

  return predicted_word

In [44]:
seed_text = "you will"
next_word = predictor(lstm_model,tokenizer,seed_text,max_len)
print(next_word)

never

In [47]:
def generateText(model, tokenizer, seed_text, n_words, max_len):
    for _ in range(n_words):

        next_word = predictor(
            model,
            tokenizer,
            seed_text,
            max_len
        )

        if next_word is None:
            break

        seed_text += " " + next_word

    return seed_text

In [48]:
seed_text = "The Meaning of Life"
generate_text = generateText(lstm_model,tokenizer,seed_text,10,max_len)
print(generate_text)

The Meaning of Life is to be loved is to be honorable to be

In [50]:
import pickle
with open("tokenizer.pickle","wb") as handle:
  pickle.dump(tokenizer,handle)

In [51]:
with open("max_len.pickle","wb") as handle:
  pickle.dump(max_len,handle)